name: publish
on: [push]
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
        with:
          fetch-depth: 1
      - name: Make all
        run: make
      - name: Upload release binaries
        uses: actions/upload-artifact@v2
        with:
          name: Upload output dirctory
          path: bin/
          if-no-files-found: error
      - name: Release Binaries
        uses: ncipollo/release-action@v1
        with:
          allowUpdates: true
          artifactErrorsFailBuild: true
          artifacts: "bin/*"
          token: ${{ secrets.GITHUB_TOKEN }}
          tag: latest
