name: publish
on: [push]
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
        with:
          fetch-depth: 1
      - name: Get TAG
        id: get_tag
        run: echo ::set-output name=TAG::${GITHUB_REF#refs/tags/}
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Login to Docker Registry
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
      - name: auto-push docker driver
        run: docker buildx create --use --name build --node build --driver-opt network=host
      - name: Release build
        id: release_build
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          platforms: linux/amd64,linux/arm/v6,linux/arm64
          build-args: |
            Version=${{ steps.get_tag.outputs.TAG }}
            GitCommit=${{ github.sha }}
          tags: |
            abdelmounaimazz/release-it:${{ github.sha }}
            abdelmounaimazz/release-it:latest
